// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrcamentosAPI.Data;

#nullable disable

namespace OrcamentosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrcamentosAPI.Models.ItemOrcamento", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("ItensOrcamento");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.MaoDeObra", b =>
                {
                    b.Property<int>("MaoDeObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaoDeObraId"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Horas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NomeTecnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroTecnicos")
                        .HasColumnType("integer");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("MaoDeObraId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("MaoDeObra");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaterialId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaterialId");

                    b.ToTable("Materiais");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor Monofasico 10A",
                            PrecoUnitario = 18.50m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor Monofasico 20A",
                            PrecoUnitario = 19.80m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor Monofasico 30A",
                            PrecoUnitario = 21.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor Bifasico 20A",
                            PrecoUnitario = 45.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor Trifasico 40A",
                            PrecoUnitario = 89.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Disjuntor DR 25A/30mA",
                            PrecoUnitario = 95.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 7,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Barramento de cobre 100A",
                            PrecoUnitario = 35.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 8,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fio 2,5mm",
                            PrecoUnitario = 3.80m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 9,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fio 4mm",
                            PrecoUnitario = 5.90m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 10,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fio 6mm",
                            PrecoUnitario = 8.50m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 11,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fio 10mm",
                            PrecoUnitario = 14.00m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 12,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cabo PP 3x2,5mm",
                            PrecoUnitario = 12.00m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 13,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Quadro distribuicao 12 disjuntores",
                            PrecoUnitario = 85.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 14,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Quadro distribuicao 24 disjuntores",
                            PrecoUnitario = 145.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 15,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Tomada 2P+T 20A",
                            PrecoUnitario = 12.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 16,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Tomada 2P+T 10A",
                            PrecoUnitario = 8.50m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 17,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Interruptor simples",
                            PrecoUnitario = 7.00m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 18,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Eletroduto 3/4",
                            PrecoUnitario = 4.20m,
                            Unidade = "m"
                        },
                        new
                        {
                            MaterialId = 19,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Abracadeira plastica pct 100",
                            PrecoUnitario = 9.00m,
                            Unidade = "pct"
                        },
                        new
                        {
                            MaterialId = 20,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Terminal ilhos 2,5mm",
                            PrecoUnitario = 1.20m,
                            Unidade = "un"
                        },
                        new
                        {
                            MaterialId = 21,
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fita isolante 18m",
                            PrecoUnitario = 5.50m,
                            Unidade = "un"
                        });
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Orcamento", b =>
                {
                    b.Property<int>("OrcamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrcamentoId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrcamentoId");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Tecnico", b =>
                {
                    b.Property<int>("TecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TecnicoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("TecnicoId");

                    b.ToTable("Tecnicos");

                    b.HasData(
                        new
                        {
                            TecnicoId = 1,
                            Ativo = true,
                            Cargo = "Tecnico Senior",
                            Nome = "Carlos Silva",
                            ValorHora = 120.00m
                        },
                        new
                        {
                            TecnicoId = 2,
                            Ativo = true,
                            Cargo = "Tecnico Junior",
                            Nome = "Ana Souza",
                            ValorHora = 80.00m
                        },
                        new
                        {
                            TecnicoId = 3,
                            Ativo = true,
                            Cargo = "Engenheiro",
                            Nome = "Roberto Lima",
                            ValorHora = 200.00m
                        });
                });

            modelBuilder.Entity("OrcamentosAPI.Models.ItemOrcamento", b =>
                {
                    b.HasOne("OrcamentosAPI.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrcamentosAPI.Models.Orcamento", "Orcamento")
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.MaoDeObra", b =>
                {
                    b.HasOne("OrcamentosAPI.Models.Orcamento", "Orcamento")
                        .WithMany("MaoDeObra")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrcamentosAPI.Models.Tecnico", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Orcamento", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("MaoDeObra");
                });
#pragma warning restore 612, 618
        }
    }
}
